version: "3.8"

services:
  postgres:
    restart: always
    image: postgres:14.5
    expose:
      - 5432
    env_file:
      - app/app/.env
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./dumps:/code/dumps

  backend:
    restart: always
    container_name: challenge_hack
    build: ./app
    command: bash -c "
      python manage.py migrate &&
      gunicorn app.wsgi:application --bind 0.0.0.0:8000 --reload"
    volumes:
      - ./app:/app
    expose:
      - 8000
    depends_on:
      - postgres

  backend_asgi:
    build: ./app
    container_name: challenge_hack_asgi
    restart: always
    expose:
      - 8100
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    command: uvicorn --host 0.0.0.0 --port 8100 --reload app.asgi:application

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "8300:80"
    depends_on:
      - backend

  redis:
    restart: always
    image: redis:7.0.4
    expose:
      - 6379
