# Generated by Django 4.1.3 on 2022-11-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_balance_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture_url",
            field=models.URLField(blank=True, verbose_name="Ссылка на аватарку"),
        ),
    ]
