# Generated by Django 4.1.3 on 2022-11-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="руб.", max_length=15, verbose_name="Валюта"
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=127, verbose_name="Имя автора"),
                ),
                (
                    "message",
                    models.CharField(max_length=1023, verbose_name="Текст сообщения"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "attachment_url",
                    models.URLField(blank=True, verbose_name="URL вложения"),
                ),
            ],
            options={
                "verbose_name": "Донат",
                "verbose_name_plural": "Донаты",
            },
        ),
    ]
